# Fine-Grained Features

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor1 = tf.Variable([[[[1], [2]],
                         [[3], [4]]]])

print(repr(tensor1))
print()
print(tensor1.numpy())

<tf.Variable 'Variable:0' shape=(1, 2, 2, 1) dtype=int32, numpy=
array([[[[1],
         [2]],

        [[3],
         [4]]]], dtype=int32)>

[[[[1]
   [2]]

  [[3]
   [4]]]]


In [3]:
depth_tensor1 = tf.nn.space_to_depth(tensor1, 2)
print(repr(depth_tensor1))
print()
print(depth_tensor1.numpy())

<tf.Tensor: id=11, shape=(1, 1, 1, 4), dtype=int32, numpy=array([[[[1, 2, 3, 4]]]], dtype=int32)>

[[[[1 2 3 4]]]]


In [4]:
# [batch, height, width, channels]
tensor2 = tf.reshape(tf.range(1, 17), [1, 4, 4, 1])
tensor2.numpy()

array([[[[ 1],
         [ 2],
         [ 3],
         [ 4]],

        [[ 5],
         [ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11],
         [12]],

        [[13],
         [14],
         [15],
         [16]]]], dtype=int32)

In [5]:
depth_tensor2 = tf.nn.space_to_depth(tensor2, 2)
depth_tensor2

<tf.Tensor: id=18, shape=(1, 2, 2, 4), dtype=int32, numpy=
array([[[[ 1,  2,  5,  6],
         [ 3,  4,  7,  8]],

        [[ 9, 10, 13, 14],
         [11, 12, 15, 16]]]], dtype=int32)>